const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"领导管理",
			            "menuJump":"列表",
			            "tableName":"lingdao"
			        }
			    ],
			    "menu":"领导管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"人力资源管理",
			            "menuJump":"列表",
			            "tableName":"renliziyuan"
			        }
			    ],
			    "menu":"人力资源管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"行政人员管理",
			            "menuJump":"列表",
			            "tableName":"xingzhengrenyuan"
			        }
			    ],
			    "menu":"行政人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"警员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"警员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"警车信息管理",
			            "menuJump":"列表",
			            "tableName":"jingche"
			        }
			    ],
			    "menu":"警车信息管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"借车记录管理",
                        "menuJump":"列表",
                        "tableName":"jiechexinxi"
                    }
                ],
                "menu":"借车记录管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"警车类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryJingche"
			        }
			        ,
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "删除",
			                "修改"
			            ],
			            "menu":"公告类型管理",
			            "menuJump":"列表",
			            "tableName":"dictionaryNews"
			        }
			    ],
			    "menu":"基础数据管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告资讯管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"公告资讯管理"
            }
            /*,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"数据备份",
			            "menuJump":"列表",
			            "tableName":"beifen"
			        },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"数据还原",
					    "menuJump":"列表",
					    "tableName":"huanyuan"
					}
			    ],
			    "menu":"数据库管理"
			}*/
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"人力资源管理",
			            "menuJump":"列表",
			            "tableName":"renliziyuan"
			        }
			    ],
			    "menu":"人力资源管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"行政人员管理",
			            "menuJump":"列表",
			            "tableName":"xingzhengrenyuan"
			        }
			    ],
			    "menu":"行政人员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"警员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"警员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"警车信息管理",
			            "menuJump":"列表",
			            "tableName":"jingche"
			        }
			    ],
			    "menu":"警车信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "审核",
	                    ],
	                    "menu":"借车记录管理",
	                    "menuJump":"列表",
	                    "tableName":"jiechexinxi"
	                }
	            ],
	            "menu":"借车记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告资讯管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告资讯管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"领导",
	    "tableName":"lingdao"
	},
	{
	    "backMenu":[
	        {
			    "child":[
			        {
			            "buttons":[
			                "查看",
                            "新增",
                            "修改",
                            "删除"
			            ],
			            "menu":"警员管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"警员管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"警车信息管理",
			            "menuJump":"列表",
			            "tableName":"jingche"
			        }
			    ],
			    "menu":"警车信息管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"借车记录管理",
	                    "menuJump":"列表",
	                    "tableName":"jiechexinxi"
	                }
	            ],
	            "menu":"借车记录管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"公告资讯管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"公告资讯管理"
	        }
	    ],
	    "frontMenu":[],
	    "hasBackLogin":"是",
	    "hasBackRegister":"否",
	    "hasFrontLogin":"否",
	    "hasFrontRegister":"否",
	    "roleName":"人力资源",
	    "tableName":"renliziyuan"
	},
	{
	        "backMenu":[
	            {
				    "child":[
				        {
				            "buttons":[
				                "查看"
				            ],
				            "menu":"警员管理",
				            "menuJump":"列表",
				            "tableName":"yonghu"
				        }
				    ],
				    "menu":"警员管理"
				}
				,{
				    "child":[
				        {
				            "buttons":[
				                "查看",
				                "新增",
				                "修改",
				                "删除"
				            ],
				            "menu":"警车信息管理",
				            "menuJump":"列表",
				            "tableName":"jingche"
				        }
				    ],
				    "menu":"警车信息管理"
				}
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"借车记录管理",
	                        "menuJump":"列表",
	                        "tableName":"jiechexinxi"
	                    }
	                ],
	                "menu":"借车记录管理"
	            }
	            ,{
	                "child":[
	                    {
	                        "buttons":[
	                            "查看"
	                        ],
	                        "menu":"公告资讯管理",
	                        "menuJump":"列表",
	                        "tableName":"news"
	                    }
	                ],
	                "menu":"公告资讯管理"
	            }
	        ],
	        "frontMenu":[],
	        "hasBackLogin":"是",
	        "hasBackRegister":"否",
	        "hasFrontLogin":"否",
	        "hasFrontRegister":"否",
	        "roleName":"行政人员",
	        "tableName":"xingzhengrenyuan"
	    },
		{
		        "backMenu":[
		            {
					    "child":[
					        {
					            "buttons":[
					                "查看",
					                "申请",
					            ],
					            "menu":"警车信息管理",
					            "menuJump":"列表",
					            "tableName":"jingche"
					        }
					    ],
					    "menu":"警车信息管理"
					}
		            ,{
		                "child":[
		                    {
		                        "buttons":[
		                            "查看",
									"还车"
		                        ],
		                        "menu":"借车记录管理",
		                        "menuJump":"列表",
		                        "tableName":"jiechexinxi"
		                    }
		                ],
		                "menu":"借车记录管理"
		            }
		            ,{
		                "child":[
		                    {
		                        "buttons":[
		                            "查看"
		                        ],
		                        "menu":"公告资讯管理",
		                        "menuJump":"列表",
		                        "tableName":"news"
		                    }
		                ],
		                "menu":"公告资讯管理"
		            }
		        ],
		        "frontMenu":[],
		        "hasBackLogin":"是",
		        "hasBackRegister":"否",
		        "hasFrontLogin":"否",
		        "hasFrontRegister":"否",
		        "roleName":"警员",
		        "tableName":"yonghu"
		    }
]
    }
}
export default menu;
